version: '3.8'
services:
  web:
    build:
      context: .
      dockerfile: dockerfile
    image: project3a_class_image
    container_name: project3a 
    ports:
      - "5005:5000"
    volumes:
      - .:/app
    environment:
      PROJECT3A_DEBUG: "1"